zend_extension=xdebug

; develop: Enables Development Helpers including the overloaded var_dump().
xdebug.mode=develop,debug
; The functionality starts when the PHP request starts, and before any PHP code is run.
xdebug.start_with_request=yes
; xdebug.client_host accepts the IP/hostname that Xdebug will connect to. IDE is the client.
; host.docker.internal = a special hostname. host.docker.internal  →  (your computer's IP from Docker's perspective)
; When Xdebug starts, connect back to my computer (the host), not inside the container.
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.idekey=PHPSTORM
